create or replace package pkg_emp as 
cursor c_emps is select * from employees_log where 1 = 2;
cursor c_dept is select * from dept_log where 1 =2;
cursor c_proj is select * from projects_log where 1 = 2;
cursor c_sal is select * from salary_log where 1 = 2;
cursor c_leave is select * from leave_log where 1 = 2;
type t_emp_log is table of c_emps%rowtype;
type t_dept_log is table of c_dept%rowtype;
type t_proj_log is table of c_proj%rowtype;
type t_sal_log is table of c_sal%rowtype;
type t_leave_log is table of c_leave%rowtype;
emp_log t_emp_log;
department_log t_dept_log;
proj_log t_proj_log;
sal_log t_sal_log;
leave_log t_leave_log;
procedure insert_emp(em_name varchar2, hredate date,man_id int, dep_id int, sal_uid number);
procedure update_emp_name(v_emp_name in varchar2, v_emp_id in number);
procedure update_manager_id(v_manager_id in number, v_emp_id in number);
procedure update_dept_id(v_dept_id in number, v_emp_id in number);
procedure update_salary_id(v_salary_id in number, v_emp_id in number);
procedure delete_emp(v_emp_id in number);
procedure insert_proj(v_manager_id number, proj_name varchar2);
procedure update_proj_manager(v_manager_id in number, v_proj_id in number);
procedure delete_proj(v_proj_id in number);
procedure insert_sal(v_designation VARCHAR2,v_da FLOAT,v_hra FLOAT,v_basic NUMBER);
procedure update_da(v_da in number, v_sal_id in number);
procedure update_hra(v_hra in number, v_sal_id in number);
procedure update_basic_pay(v_basic_pay in number, v_sal_id in number);
procedure delete_sal(v_sal_id in number);
procedure insert_dept(d_dept_name varchar2);
procedure update_dept(d_name varchar2 , d_dept_id number);
procedure delete_dept(d_id number);
procedure insert_leave(v_emp_id in number, v_date in date, v_reason in varchar2);
procedure log_emp;
procedure log_sal;
procedure log_leave;
procedure log_proj;
procedure log_dept;
function search_emp(v_emp_id in number) return boolean;
function search_dept(d_dept_id in number) return boolean;
function search_sal(v_sal_id in number) return boolean;
function search_proj(v_proj_id in number) return boolean;
end pkg_emp;